environment:
  size:
    x: 20
    y: 20
    z: 10

  max_steps: 200

auv:
  start_position: [2.0, 2.0, 2.0]

  speed: 1.0

  radius: 0.5

goal:
  position: [18.0, 18.0, 8.0]
  radius: 1.0

obstacles:
  count: 5
  radius: 1.0

safety:
  safety_distance: 2.0
  max_nearby_obstacles: 5
